include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "Modol/**"  # Exclude the Modol directory from analysis
  
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false

linter:
  rules:
    # Error rules
    - avoid_print: false  # Allow print statements for debugging
    - prefer_const_constructors: false  # Disabled for flexibility
    - prefer_const_literals_to_create_immutables: false  # Disabled for flexibility
    - prefer_const_declarations: false  # Disabled for flexibility
    
    # Style rules
    - camel_case_types: true
    - file_names: true
    - non_constant_identifier_names: true
    - constant_identifier_names: true
    
    # Pub rules
    - package_names: true
    
    # Disabled rules for flexibility
    - lines_longer_than_80_chars: false
    - avoid_web_libraries_in_flutter: false
    - use_build_context_synchronously: false  # Allow async operations with BuildContext
    - avoid_unnecessary_containers: false  # Disabled for UI flexibility
    - sort_child_properties_last: false  # Disabled for readability
    - prefer_single_quotes: false  # Allow both single and double quotes
    
    # Essential rules only
    - avoid_void_async: true
    - cancel_subscriptions: true
    - close_sinks: true
    - use_full_hex_values_for_flutter_colors: true
    - use_key_in_widget_constructors: false  # Disabled as we use super.key