name: Build Signed APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-signed-apk:
    name: Build Signed APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build Signed APK
        run: flutter build apk --release

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: signed-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 30
