name: Flutter CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
        channel: 'stable'

    - name: Install Android SDK Build-Tools
      run: | 
        sudo apt-get update
        sudo apt-get install -y android-sdk-build-tools
        # Accept Android licenses
        yes | sdkmanager --licenses

    - name: Get Flutter dependencies
      run: flutter pub get

    - name: Build Android APK
      run: flutter build apk --release

    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk


