name: Flutter CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
        channel: 'stable'

    - name: Install Android SDK Build-Tools
      uses: android-actions/setup-android@v2
      with:
        api-level: 34
        build-tools: 34.0.0
        ndk: 25.1.8937393 # Optional, specify if needed
        # Accept Android licenses is handled by setup-android action


    - name: Add Android properties for compatibility
      run: |
        echo "android.useAndroidX=true" >> android/gradle.properties
        echo "android.enableJetifier=true" >> android/gradle.properties

    - name: Get Flutter dependencies
      run: flutter pub get

    - name: Build Android APK (Debug)
      run: flutter build apk --debug

    - name: Upload Android APK (Debug)
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: build/app/outputs/flutter-apk/app-debug.apk


